### ISSUE TITLE
Deploy memory on the remote server

### ISSUE THREAD

**Issue by oktayda** [HE-Arc/Memories#13]
Purpose to test the deployment

**Comment by boillatil** [comment]
Etapes pour les futurs déploiement :
- Git pull
- Dans "app/Http/Middleware/TrustProxies.php", modifier la la ligne : protected $proxies = '*';
- Mettre à jour le paquet grimzy avec la commande suivante : composer require grimzy/laravel-mysql-spatial:^5.0
- Mise à jour du composer : composer update
